<a href="https://colab.research.google.com/github/reggieHabas/DS-Unit-1-Sprint-2-Statistics/blob/master/module2/LS_DS_122_Chi2_Tests_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment - Practice Chi^2 Tests

Use the following dataset relating to math scores of students in two different Portugese schools:

<https://archive.ics.uci.edu/ml/datasets/Student+Performance>

### 1) Load the dataset specifically relating to math scores as a new dataframe.

There are two datasets in the `student.zip` file, make sure you use `student-mat.csv`.


In [13]:
# imports
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind, ttest_1samp 
from scipy.stats import chisquare
import scipy.stats as stats

In [2]:
# unzip folder
!unzip student\ \(1\).zip

Archive:  student (1).zip
  inflating: student-mat.csv         
  inflating: student-por.csv         
  inflating: student-merge.R         
  inflating: student.txt             


In [6]:
# read in the data
student = pd.read_csv('student-mat.csv', sep=';')

In [7]:
# check out the data
student.head()

school sex  age address famsize Pstatus  ...  Walc  health absences  G1  G2  G3
0     GP   F   18       U     GT3       A  ...     1       3        6   5   6   6
1     GP   F   17       U     GT3       T  ...     1       3        4   5   5   6
2     GP   F   15       U     LE3       T  ...     3       3       10   7   8  10
3     GP   F   15       U     GT3       T  ...     1       5        2  15  14  15
4     GP   F   16       U     GT3       T  ...     2       5        4   6  10  10

[5 rows x 33 columns]

### 2) Use Chi^2 tests and `stats.chi2_contingency()` to identify:
 - Two pairs of variables that are dependent (are associated with one another).
 - Two pairs of variables that are independent (have no significant relationship).

Does it make intuitive sense why the variables in these pairs might or might not show a relationship to one another? 


In [8]:
# Variables: 
time = pd.crosstab(student['traveltime'], student['studytime'])
time

studytime    1    2   3   4
traveltime                 
1           60  133  47  17
2           31   51  16   9
3           11   11   1   0
4            3    3   1   1

In [17]:
# Test time at 95% confidence interval
# Null Hypo = variables are dependent
# Alt hypo = variables are independent
stats.chi2_contingency(time)

# Results = Do not reject the null hypo. 
# Variables are dependent

(11.200170929144969,
 0.26223746329595793,
 9,
 array([[ 68.3164557 , 128.82531646,  42.29113924,  17.56708861],
        [ 28.44303797,  53.63544304,  17.60759494,   7.31392405],
        [  6.11392405,  11.52911392,   3.78481013,   1.5721519 ],
        [  2.12658228,   4.01012658,   1.3164557 ,   0.54683544]]))

In [18]:
# Variables: age & failures
af = pd.crosstab(student['age'], student['failures'])
af

failures   0   1  2  3
age                   
15        71   3  5  3
16        88  10  4  2
17        84   8  2  4
18        63  16  1  2
19         5  13  3  3
20         1   0  2  0
21         0   0  0  1
22         0   0  0  1

In [19]:
# test af at 95% confidence interval
# Null Hypo = variables are dependent
# Alt hypo = variables are independent
stats.chi2_contingency(af)

# Results = reject the null hypo
# Variables are independent

(144.29903924777085,
 2.1137084383846074e-20,
 21,
 array([[6.47696203e+01, 1.03797468e+01, 3.52911392e+00, 3.32151899e+00],
        [8.21468354e+01, 1.31645570e+01, 4.47594937e+00, 4.21265823e+00],
        [7.74075949e+01, 1.24050633e+01, 4.21772152e+00, 3.96962025e+00],
        [6.47696203e+01, 1.03797468e+01, 3.52911392e+00, 3.32151899e+00],
        [1.89569620e+01, 3.03797468e+00, 1.03291139e+00, 9.72151899e-01],
        [2.36962025e+00, 3.79746835e-01, 1.29113924e-01, 1.21518987e-01],
        [7.89873418e-01, 1.26582278e-01, 4.30379747e-02, 4.05063291e-02],
        [7.89873418e-01, 1.26582278e-01, 4.30379747e-02, 4.05063291e-02]]))

In [20]:
# Variables: freetime & studytime
ft_st = pd.crosstab(student['freetime'], student['studytime'])
ft_st

studytime   1   2   3   4
freetime                 
1           2  11   3   3
2          19  28  11   6
3          35  82  29  11
4          29  61  21   4
5          20  16   1   3

In [21]:
# test ft_st at 95% confidence interval
# Null Hypo = variables are dependent
# Alt hypo = variables are independent
stats.chi2_contingency(ft_st)

# Results = reject the null hypo
# Variables are independent

(23.53045426913059,
 0.023545617681757027,
 12,
 array([[ 5.05063291,  9.52405063,  3.12658228,  1.29873418],
        [17.01265823, 32.08101266, 10.53164557,  4.37468354],
        [41.73417722, 78.69873418, 25.83544304, 10.73164557],
        [30.56962025, 57.64556962, 18.92405063,  7.86075949],
        [10.63291139, 20.05063291,  6.58227848,  2.73417722]]))

In [22]:
# Variables: goout & health
gh = pd.crosstab(student['goout'], student['health'])
gh

health   1   2   3   4   5
goout                     
1        4   3   5   2   9
2       10   7  29  10  47
3       13  17  37  26  37
4       14  10  14  19  29
5        6   8   6   9  24

In [23]:
# test ft_st at 90% confidence interval
# Null Hypo = variables are dependent
# Alt hypo = variables are independent
stats.chi2_contingency(gh)

# Results = reject the null hypo
# Variables are independent

(25.5796121467849,
 0.060237858840016874,
 16,
 array([[ 2.73670886,  2.62025316,  5.29873418,  3.84303797,  8.50126582],
        [12.2556962 , 11.73417722, 23.72911392, 17.21012658, 38.07088608],
        [15.46835443, 14.81012658, 29.94936709, 21.72151899, 48.05063291],
        [10.23291139,  9.79746835, 19.81265823, 14.36962025, 31.78734177],
        [ 6.30632911,  6.03797468, 12.21012658,  8.8556962 , 19.58987342]]))

### 3) Use NumPy to perform your own chi^2 test "from scratch" 

Pick any of the chi^2 tests that you ran in part 2 and try them on your own. You should get the same results that Scipy got for all four values returned from `chi2_contingency()`

In [25]:
gh = pd.crosstab(student['goout'], student['health'], margins=True)
gh

health   1   2   3   4    5  All
goout                           
1        4   3   5   2    9   23
2       10   7  29  10   47  103
3       13  17  37  26   37  130
4       14  10  14  19   29   86
5        6   8   6   9   24   53
All     47  45  91  66  146  395

In [32]:
row_sums = gh.iloc[0:5, 5].values
col_sums = gh.iloc[5, 0:5].values

print(row_sums)
print(col_sums)

[ 23 103 130  86  53]
[ 47  45  91  66 146]


In [35]:
total = gh.loc['All', 'All']
total

395

In [33]:
student.shape[0]

395

In [36]:
expected = []
for i in range(len(row_sums)):
  expected_row = []
  for column in col_sums:
    expected_val = column*row_sums[i]/total
    expected_row.append(expected_val)
  expected.append(expected_row)

expected = np.array(expected)
print(expected.shape)
print(expected)

(5, 5)
[[ 2.73670886  2.62025316  5.29873418  3.84303797  8.50126582]
 [12.2556962  11.73417722 23.72911392 17.21012658 38.07088608]
 [15.46835443 14.81012658 29.94936709 21.72151899 48.05063291]
 [10.23291139  9.79746835 19.81265823 14.36962025 31.78734177]
 [ 6.30632911  6.03797468 12.21012658  8.8556962  19.58987342]]


In [41]:
observed = pd.crosstab(student['goout'], student['health']).values
print(observed.shape)
observed

(5, 5)


array([[ 4,  3,  5,  2,  9],
       [10,  7, 29, 10, 47],
       [13, 17, 37, 26, 37],
       [14, 10, 14, 19, 29],
       [ 6,  8,  6,  9, 24]])

In [42]:
chi_squared = ((observed - expected)**2/(expected)).sum()
print(f"Chi-Squared: {chi_squared}")

Chi-Squared: 25.5796121467849


In [43]:
# Calculate degrees of freedom
dof = (len(row_sums)-1)*(len(col_sums)-1)
print(f"Degrees of Freedom: {dof}")

Degrees of Freedom: 16


## Stretch goals:

### 1. Refactor your code so it is elegant, readable, and holds reusable code in functions.

In [ ]:
# YOUR WORK HERE



### 2. Check For Understanding - Study and write your own explanations/definitions for these topics:

- What is a sample "estimate" in statistics?

- What are hypothesis test? How are they useful?

- What is a "null hypothesis?"

- What is a p-value and what does it represent?

- What does it mean for something to be "statistically significant?"

- What is a test statistic and how does it relate to a p-value?

- What are "degrees of freedom" and how are they calculated in a 1-sample, 2-sample, and chi^2 test for independence?

## Resources

- [Interactive visualize the Chi-Squared test](https://homepage.divms.uiowa.edu/~mbognar/applets/chisq.html)
- [Calculation of Chi-Squared test statistic](https://en.wikipedia.org/wiki/Pearson%27s_chi-squared_test)
- [Visualization of a confidence interval generated by R code](https://commons.wikimedia.org/wiki/File:Confidence-interval.svg)
- [Expected value of a squared standard normal](https://math.stackexchange.com/questions/264061/expected-value-calculation-for-squared-normal-distribution) (it's 1 - which is why the expected value of a Chi-Squared with $n$ degrees of freedom is $n$, as it's the sum of $n$ squared standard normals)